// Copyright 2025 QMK -- generated source code only, font retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// This file was auto-generated by `qmk painter-convert-font-image --input D:/11_vial/vial-qmk/keyboards/omni_kbd/font/st2_mono16.png --output D:/11_vial/vial-qmk/keyboards/omni_kbd/font --no-ascii False --unicode-glyphs  --format mono2 --no-rle False`

#pragma once

#include <qp.h>

extern const uint32_t font_st2_mono16_length;
extern const uint8_t  font_st2_mono16[1222];
