SRC += quantum/os_detection.c

VIA_ENABLE = yes
VIAL_ENABLE = yes

TAP_DANCE_ENABLE = yes
COMBO_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
MAGIC_ENABLE = yes
GRAVE_ESC_ENABLE = yes
NKRO_ENABLE = yes

DETECTED_HOST_OS_ENABLE = yes
OS_DETECTION_ENABLE = yes
