/* SPDX-License-Identifier: GPL-2.0-or-later */

#pragma once

#define VIAL_KEYBOARD_UID {0x71, 0xBB, 0xFD, 0x03, 0x12, 0xCF, 0xC5, 0x03}

#define VIAL_UNLOCK_COMBO_ROWS { 0, 2 }

#define VIAL_UNLOCK_COMBO_COLS { 0, 13 }

// Toggle
#define ONESHOT_TAP_TOGGLE 2
#define TAPPING_TOGGLE 2

// Retro tapping
#define DUMMY_MOD_NEUTRALIZER_KEYCODE KC_F18
#define MODS_TO_NEUTRALIZE { MOD_BIT(KC_LEFT_ALT), MOD_BIT(KC_LEFT_GUI), MOD_BIT(KC_RIGHT_GUI), MOD_BIT(KC_LEFT_CTRL)|MOD_BIT(KC_LEFT_SHIFT) }
#define VIAL_TAP_DANCE_ENTRIES 100

#define QUICK_TAP_TERM 0
#define TAPPING_TERM 180
#define DYNAMIC_KEYMAP_LAYER_COUNT 10
#define OS_DETECTION_KEYBOARD_RESET
