CONSOLE_ENABLE = no
COMBO_ENABLE = yes
KEY_OVERRIDE_ENABLE = no
MOUSEKEY_ENABLE = no
LTO_ENABLE = yes
COMMAND_ENABLE = no
BOOTMAGIC_ENABLE = no
AUDIO_ENABLE = no
MAGIC_ENABLE = no
QMK_SETTINGS = no
VIA_ENABLE = yes
VIAL_ENABLE = yes

